### ISSUE TITLE
An open-source video understanding model that supports audio input

### ISSUE THREAD

**Issue by AshOneN** [BradyFU/Video-MME#11]
In the open-source model, minigpt4-video seems to support audio and subtitle input? Convert audio input into subtitles with whisper, and the paper says that there is no open source model that supports audio input

**Comment by BradyFU** [comment]
Hi, thanks for your attention! : )
"It is regrettable that none of the open-sourced models support audio input."
"the open-sourced models" means the open-sourced models listed in our paper.
