### ISSUE TITLE
The settings of videollava when reproducing

### ISSUE THREAD

**Issue by Kongyj** [BradyFU/Video-MME#13]
Hi, I was reproducing the performance of Video-LLaVA-7B (https://huggingface.co/LanguageBind/Video-LLaVA-7B) on the video-mme benchmark. I found that the performance is very poor when I use the video inference code in Video-LLaVA-7B (Hugging Face) since it always responds with the answer "A." I have extracted 8 frames and corresponding subtitles for each video before inference according to your instructions. So I think it may be due to differences in settings. 

Also, I have met the same problem in Chat-Univi. 

Could you please tell me the settings and parameters that you used when running the Video-LLaVA, such as the conv_mode, prompt, and all the parameters you used in the "model.generate()" function?
Thank you so much.

For me, I use the following settings:
```
for i, question in enumerate(data['questions']):
    inp= f'''This video's subtitles are listed below:\n{data['subtitles']}\nSelect the best answer to the following multiple-choice question based on the video. Respond with only the letter (A, B, C, or D) of the correct option. \n{question['question']}\n{question['options'][0]}\n{question['options'][1]}\n{question['options'][2]}\n{question['options'][3]}\nThe best answer is:'''
    conv_mode = "llava_v1"
    conv = conv_templates[conv_mode].copy()
    roles = conv.roles
    inp = ' '.join([DEFAULT_IMAGE_TOKEN] * model.get_video_tower().config.num_frames) + '\n' + inp
    conv.append_message(conv.roles[0], inp)
    conv.append_message(conv.roles[1], None)
    prompt = conv.get_prompt()
    input_ids = tokenizer_image_token(prompt, tokenizer, IMAGE_TOKEN_INDEX, return_tensors='pt').unsqueeze(0).cuda()
    stop_str = conv.sep if conv.sep_style != SeparatorStyle.TWO else conv.sep2
    keywords = [stop_str]
    stopping_criteria = KeywordsStoppingCriteria(keywords, tokenizer, input_ids)
    with torch.inference_mode():
        output_ids = model.generate(
            input_ids,
            images=tensor,
            do_sample=False,
            num_beams=1,
            max_new_tokens=1024,
            use_cache=True,
            stopping_criteria=[stopping_criteria])
    outputs = tokenizer.decode(output_ids[0, input_ids.shape[1]:]).strip()
    data['questions'][i]['response'] = outputs.replace("</s>", "")
```

**Comment by BradyFU** [comment]
Hi， thanks for your attention! Could you leave your WeChat ID? We could communicate further via WeChat.

**Comment by Kongyj** [comment]
> Hi， thanks for your attention! Could you leave your WeChat ID? We could communicate further via WeChat.

Of course! My WeChat ID is Kongyj201314. Thank you so much!

**Comment by klauscc** [comment]
I hope you have solved this issue. Do you mind sharing the evaluation code for VideoLLaVA-Next? Thanks!

**Comment by kabutohui** [comment]
I meet the same problem too, when use the suggested prompt format：
> Select the best answer to the following multiple-choice question based on the video. Respond with only the letter (A, B, C, or D) of the correct option. 
[Question]
The best answer is:

The video-llava response always "A". Have you fixed this problem? THX.

**Comment by BradyFU** [comment]
Hi, for those models that have a multiple-choice prompt, we use its specific prompt, such as "Answer with the option’s letter from the given choices directly", which is widely used in the LLaVA series.
If not, we use our default prompt "Select the best answer to the following multiple-choice question based on the video. Respond with only the letter (A, B, C, or D) of the correct option..."
