### ISSUE TITLE
Fix leaderboard sorting by LLM parameters on project page

### ISSUE THREAD

**Issue by maxbourke** [BradyFU/Video-MME#15]
**Minor issue with project homepage: Sort by LLM parameters not working**

**URL:** https://video-mme.github.io/home_page.html#leaderboard

**Description:**
There is a minor issue with the sorting functionality in the leaderboard table. Clicking on the "LLM Params" header currently results in a lexical sort, not a numeric sort. The complication is the use of human readable numerical suffixes which is causing JS to parse these fields as text.

**Steps to Reproduce:**
1. Go to the homepage at https://video-mme.github.io/home_page.html#leaderboard.
2. Click the "LLM Params" header in the leaderboard table.

**Expected Result:**
The table sorts by ***numeric*** parameter size (e.g., in ascending order 7B comes before 34B).

**Actual Result:**
The table sorts by ***lexical*** parameter size (e.g., in ascending order 34B comes before 7B).

**Screenshots:**
![image](https://github.com/BradyFU/Video-MME/assets/74052986/b16f6a7f-1cef-49be-8997-0cdb1982d1ce)

**Suggestion:**
I can see the table uses the SortTable library (https://github.com/stationer/SortTable). It may require a custom or modified sort function for the "LLM Params" column to handle numeric sorting, or a hidden numeric column (where 34B is parsed to Number("34") * 1e9 and so on). Unfortunately JS is well outside my wheelhouse but could be a good first issue for someone.

**Comment by BradyFU** [comment]
Hi, I am sorry that I didn't reply in time due to some things in recent days.
Sincerely thanks for your valuable suggestions. We are fixing this problem.
