### ISSUE TITLE
Certificates of the videos

### ISSUE THREAD

**Issue by Ciel127** [BradyFU/Video-MME#16]
Thanks for your excellent work,I would like to further research on your dataset,could you please tell me how to find the certificates of the questions in the Video-MME dataset?I can only find video_id、duration、domain、question、options、answers on your huggingface,I will appreciate it if you can tell me how to get the information of the certificates of your dataset.

**Comment by BradyFU** [comment]
Hi, could you leave your WeChat ID? We could communicate further via WeChat.

**Comment by EricLina** [comment]
Same question.
