### ISSUE TITLE
Question about the evaluation script in the leaderboard

### ISSUE THREAD

**Issue by Richar-Du** [BradyFU/Video-MME#19]
Thanks for your awesome work in Video-MME! 

Does the accuracy of all the models in the leaderboard are calculated according to this script: https://github.com/thanku-all/parse_answer/blob/main/eval_your_results.py?

**Comment by BradyFU** [comment]
Yeah, Richar, you could also use this script.

**Comment by Richar-Du** [comment]
Got it, thanks for your reply :)
