### ISSUE TITLE
Hi, How to evaluate image-vlm model on your video benchmark?

### ISSUE THREAD

**Issue by dragen1860** [BradyFU/Video-MME#2]
Dear author:
   I looks the benchmark is really comprehensive and very helpful in video vlm domain. thanks.
   I wonder how to conduct the experiment on some typical image-based vlm models such as internvl-1.5, because generally it is image-based vlm but not video vlm.  Could you kindly share the usage code to evaluate the internvl-v1.5?

**Comment by BradyFU** [comment]
Hi, thanks for your attention!
We can feed multiple video frames into internvl-v1.5. The image-based vlms usually have the ability to generalize to multiple images. 
The case can be find here:
https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5#model-usage
Please note the "# multi-round multi-image conversation".

**Comment by dragen1860** [comment]
@BradyFU ok. So you did not finetunning the image vlm but test it directly on video--mme? thanks.

**Comment by BradyFU** [comment]
We directly test without finetuning.
