### ISSUE TITLE
GPT4o evaluation

### ISSUE THREAD

**Issue by resi1ience** [BradyFU/Video-MME#20]
Thanks for your great work!

However, I encounter problems when evaluating gpt4o. May I ask how to put 384 frames into gpt4o's input? My API will report error with it.

Any response will be greatly appreciated

**Comment by BradyFU** [comment]
Hi, you need to update your API account to support 128K context.

**Comment by resi1ience** [comment]
Thank you! I'll give it a try

**Comment by BradyFU** [comment]
You are welcome ：）

**Comment by HYUNJS** [comment]
Hi. Thanks for your great work!
I'm encountering a similar issue when trying to use more frames (e.g. 384) with GPT-4o.  Could you clarify what you mean by "update your API account"? The only thing I'm aware of is the "Usage Tier," but mine is already set to a high level.

For details, when I attempt to use GPT-4o with 338 frames in low-resolution mode, I receive the following error:
`openai.BadRequestError: Error code: 400 - {'error': {'message': 'Too many images in request: 251, maximum allowed: 250.', 'type': 'invalid_request_error', 'param': None, 'code': None}}`
