### ISSUE TITLE
Results of LLaVA-Next-video-7B

### ISSUE THREAD

**Issue by farewellthree** [BradyFU/Video-MME#24]
Hi, thanks for the great benchmark! Are there any official results of LLaVA-Next-video-7B? My implementation seems too low.

**Comment by Wang-Xiaodong1899** [comment]
Hi @farewellthree , I found the evaluation of LLaVA-Next-video-7B is higher than the tables, but my implementation is also too low.

**Comment by BradyFU** [comment]
Hi! I am very sorry for the late reply. If you have any questions, please leave a WeChat ID (or send it to bradyfu24@gmail.com) and I will help solve it.
Thanks for your attention!
