### ISSUE TITLE
What's the license of Video-MME?

### ISSUE THREAD

**Issue by whwu95** [BradyFU/Video-MME#25]
Hello,

I would like to use this dataset for academic research. However, I noticed that there is no license information provided on the Hugging Face page for this dataset. Could you please clarify what the license is? Specifically, is it covered under CC-BY-4.0 or Apache 2.0?

Thank you for your assistance!

**Comment by BradyFU** [comment]
Hi Wenhao! I am very sorry for the late reply. If you have any questions, please leave a WeChat ID (or send it to [bradyfu24@gmail.com](mailto:bradyfu24@gmail.com)) and I will help solve it.
Thanks for your attention!
