### ISSUE TITLE
Some subtitles are missing

### ISSUE THREAD

**Issue by Richar-Du** [BradyFU/Video-MME#28]
There are 468 questions missing the corresponding subtitles (e.g., 4IenX7OHumk), where can I download the complete subtitles? Thanks in advance :)

**Comment by BradyFU** [comment]
Hi, thanks for your attention. All long videos have subtitles, but short and medium videos do not.

**Comment by BradyFU** [comment]
Hello yifan, if it is convenient, you could send your WeChat ID to my email bradyfu24[at]gmail[dot]com and keep in touch.
