### ISSUE TITLE
❓[Question] How to acquire the subtitles of all videos?

### ISSUE THREAD

**Issue by clownrat6** [BradyFU/Video-MME#6]
Firstly, thanks to the author team for providing such a useful video llm evaluation benchmark. I have some doubts abouts the w/ sub settings.

According to my practice, it seems that not all videos have subtitles. I wonder that if this is correct for measuring metric under w/ sub settings of the benchmark.

**Comment by BradyFU** [comment]
Hi,
Thanks for your attention on our work!
All of the long videos, and most of the short and medium videos have subtitles.
The comprehension of long videos is more rely on subtitles.

If possible, you could leave your WeChat ID or send it to bradyfu24@gmail.com.
We can further contact through WeChat.
