### ISSUE TITLE
Updated results of VideoChat2 and some problems

### ISSUE THREAD

**Issue by Andy1621** [BradyFU/Video-MME#7]
Hi! Thanks for your efforts in building more comprehensive video benchmarks. 

## VideoChat2-Mistral
Recently, we have updated [VideoChat2](https://github.com/OpenGVLab/Ask-Anything/tree/main/video_chat2) with Mistral-7B and better instruction data. Since the official testing script of Video-MME is not provided, I have tested our VideoChat2 based on the logic of [MVBench](https://github.com/OpenGVLab/Ask-Anything/blob/main/video_chat2/mvbench.ipynb).

## Results
Here are the results. For VideoChat2_text, we input the fake videos, which are full of zeros:

<div align="left">
<table width="100%">
    <tr align="center">
        <th>Model</th>
        <th>Short w/o subs</th>
        <th>Short w/ subs</th>
        <th>Medium w/o subs</th>
        <th>Medium w/ subs</th>
        <th>Long w/o subs</th>
        <th>Long w/ subs</th>
        <th>Overall w/o subs</th>
        <th>Overall w/ subs</th>
    </tr>
    <tr align="center">
        <th>VideoChat2<br>(Mistral)</th>
        <td>49.6</td>
        <td>56.0</td>
        <td>38.4</td>
        <td>55.1</td>
        <td>39.0</td>
        <td>52.6</td>
        <td>42.3</td>
        <td>54.6</td>
    </tr>
    <tr align="center">
        <th>VideoChat2-HD<br>(Mistral)</th>
        <td>54.7</td>
        <td>59.5</td>
        <td>41.3</td>
        <td>53.6</td>
        <td>39.8</td>
        <td>53.9</td>
        <td>45.3</td>
        <td>55.7</td>
    </tr>
    <tr align="center">
        <th>VideoChat2_text<br>(Mistral)</th>
        <td>23.5</td>
        <td>39.3</td>
        <td>25.2</td>
        <td>47.7</td>
        <td>24.2</td>
        <td>45.6</td>
        <td>24.6</td>
        <td>45.6</td>
    </tr>
</table>
</div>

Here are the JSON files:
- [videochat2_without_subs.json](https://github.com/user-attachments/files/15737709/videochat2_without_subs.json)
- [videochat2_with_subs.json](https://github.com/user-attachments/files/15737711/videochat2_with_subs.json)
- [videochat2_hd_without_subs.json](https://github.com/user-attachments/files/15737707/videochat2_hd_without_subs.json)
- [videochat2_hd_with_subs.json](https://github.com/user-attachments/files/15737708/videochat2_hd_with_subs.json)
- [videochat2_text_without_subs.json](https://github.com/user-attachments/files/15737705/videochat2_text_without_subs.json)
- [videochat2_text_with_subs.json](https://github.com/user-attachments/files/15737706/videochat2_text_with_subs.json)

:warning: Our current version has some missing videos and subtitles:
   - Missing videos: Short (2), Medium (3), Long (11)
   - Missing subtitles: Short (93), Medium (52), Long (10)

### About missing videos and subtitles
Considering some of the videos are no longer available, could you provide the raw videos?
```shell
#######Missing Videos#######
----------short: 2----------
['6YhlYu70uNA', 'j_9Fa9Uk8cA']
----------medium: 3----------
['Vo6HXsHgizc', 'azZZZbSwLQght', '3fGlUydVjRE']
----------long: 11----------
['Ry2dJuJ-9UE', 'cL27iZTOSNU', 'LvrcYs00wLk', 'mIk8MyVMLt0', 'k9n7kGQmFzI', '_eJsOYC8SVU', 'TYmHe20p_zU', 'r1PoSdFWvQg', 'N62mrplIygc', 'JLg4Rd6ukcg', 'azJ5pk5reX0']
#######Missing Subtitles#######
----------short: 93----------
['HwnB8aCn8yE', 'sUDY-SMREtA', 'OE5S-NbNsro', '5wLv3pCqZ9o', 'O0qVPW1fUn4', 'tX8a00l_Dfs', 'iZYLeIJwe4w', 'ebzbKa32kuk', '6YhlYu70uNA', 'fo0Hmch2YS0', 'M7WOXFvwbSY', 'RvnC--JjDBw', 'DF_J3vCcbBA', 'm4qhFFdHTCc', 'aBdQQxgxDrY', 'tF4DML7FIWk', 'M69Sn3OERZo', 'PU-XOFIJMlg', 'rQhLWHtHyiM', '2Qno7H4BwAU', 'a0AGwUACt7E', 'qu9ImFMLYxw', 'Qgr4dcsY-60', 'tGdL-34L-GE', 's50vvwTystA', 'y6ReUXtm_VE', 'ykJ7pyr87Qc', '4V6G0qYVoBg', 'uF3zNOthLAg', '6Z_XNM_iT4g', 'fJ-hp5Jlbv0', 'of62s85uMMs', '80p80ynsZ78', 'Kv1JXuOkAfk', 'lsfEHOtYGyk', 'rj6rJzs029A', 'QUmkzhUQoEA', 'KZu5iE7yrPI', 'JP67IM1LX-M', '_KU4X06VNiE', 'BkiTScinYOQ', '-qTAeVGl_e8', 'CHlJdMVLV2s', 'E895PNqSgEI', 'FsLaTZmP6Uw', 'tbKTfX5Az6w', 'TblFD8H4j94', '8np5YKYx3sU', 'NjxJY7P-Qpo', 'HiJb_2dvuHc', 'QhL6ICNQ_So', 'iOOseoPiw8E', 'PSC_HUeqaUk', 'jznsxDcKSnE', 'QGHVpr8FIN8', 'lNKtsi2Cu0E', 'V_skpmEXebM', 'QtKT3q7xB4M', '026dzf-vc5g', 'KEy2iCzpce4', 'dH8l--46j6s', 'VmNBt1tzC6k', '5Knkqo-lYF0', 'BrrDT_uYQsg', 'jmE9y0vv2aM', 'fSDq8CPXHQM', 'D61jenC5oBA', 'OCTekmo_szs', 'g1MCVp5xICM', 'BiJtPU9uP0c', 'OQAf_rTw7n8', 'ufZMrlZRn8o', 'IKtnfFHjERg', 'zPx3EibuO_w', 'J2rlJV7zKZw', 'v0m3E_uSyFg', 'NAahAX62MZ0', 'YZ11C-U7S8I', 'jb-To6qJcxU', 'frX8GujpmkI', 'j_9Fa9Uk8cA', 'ZfNSxRiYfZQ', 'PaC3CEkCD6k', '8e05W-wi38g', 'Atf_Af1q_5w', 'Kn10Jf1x24Q', 'vszWsYOdnPg', 'ZHWZf1Z4B5k', '6Cr_8tvvQ0k', 'H8fbAFOMTp4', 'tGdL-34L-GE', 'MiPw-RZMHCQ', 'UcL6WlcyBcI']
----------medium: 52----------
['1pHkv4KUiFY', 'z2APU5ob9Og', '7Hk9jct2ozY', 'AmrrSfiMxGA', 'Vo6HXsHgizc', 'QI9VIulqTCA', '2za5RwplXdI', 'ZN6kyy2SXnk', 'uMIohuKRq58', 'OApAF--FqLA', 'Gokw6n0qf-w', '0FM64MrRuZE', 'Rh8sz6ZnXM4', 'erjwCQ-UZyw', 'H54zMD-9Q-8', 'QnGwAUTM1fY', 'ACvLYz9nHvg', '2NOcM1HoRRg', '6ksaVHtfBG8', 'UmIYanq5gH8', 'SBssmtYTJpM', 'u_f0697yLBI', 'zW87tVnDKIU', 'vf3sPa2W0sA', 'e-XGSYnhUjg', 'ZFtxvf72NxA', 'vgWlRdNOGx4', 'G-mmtUxSt5k', 'hQYRDNl-lGI', 'awHc8IySU-I', 'CwzjlmBLfrQ', 'BEIVOKz4zXw', 'PB06auioy0Y', '_w4XRiUVfY4', 'azZZZbSwLQght', 'qNWL4S5bDt4', 'a8IGDMrohnY', '1sTNqJVrqx8', 'zbvamKv81o0', 'VfSIqKSiguc', 'dy8AvyRlXpQ', 'hZ8DmOpRTVc', 'EFD9BLgMVK8', 'HZJXPm0nhgY', '3EQzRz-V7uE', '_CqKv0Y1FB0', 'BVJGvKaFG7U', 'cFqLEwAvaHI', 'VoJ-Ey6q8uM', 'l73rmrLTHQc', 'p9uIBCDhyr0', '3fGlUydVjRE']
----------long: 10----------
['Sp2nxlrQ89w', 'cL27iZTOSNU', 'LvrcYs00wLk', 'mIk8MyVMLt0', 'k9n7kGQmFzI', 'yh-EHgkFci4', '7TydWUguPRU', 'JLg4Rd6ukcg', 't23Zi0DBSiI', '4IenX7OHumk']
```

### About the processing of long subtitles
During the testing, I found that some subtitles have extremely long tokens. How do you process them? For me, I simply sample the beginning and the end of the subtitles.

### About the performances
**It is interesting that most of the methods achieve not bad performances with only 10 frames, since the videos are much longer than those in the previous benchmarks.**
I have conducted some experiments with fake videos, as shown in the VideoChat_text. The results show that without any vision information or subtitles, the model answers randomly. The subtitles provide enough information to answer the questions, which reflects that **the current benchmark may still have some bias of language**. 
Moreover, from the results, we can find that **the larger LLMs lead to better performances**
- 7B => 40+
- 20B => 50+
- Closed-sourced => 60+

**Comment by BradyFU** [comment]
Hi, thanks for your attention on our work!

We have conducted corresponding experiments, and find that the subtitles always contain some useful information, which is fundamentally hard to eliminate, especially for the longer videos and some video classes like _News_.

We have tried to make the question as relevant as possible to the visual content, but as mentioned above, the model will inevitably get some information from the subtitles.

We find that _video frames + subtitles_ are always better than _frames only_ or _subtitles only_, which indicates the multi-modal characteristics of our dataset, that is, both video frames and subtitles can provide certain information, but they need to be integrated to obtain the best results.

In addition, if you sample ten frames of the video, you should only feed the subtitles corresponding to the ten frames, instead of all substitles. We will give a detailed explanation on the use of substitles soon.

For the question about the dataset, you could send an email to videomme2024@gmail.com.
